#!/usr/bin/python2
# -*- coding: utf-8 -*-
import sys
import os
import aletkutusu as alt
import debian
import time

if os.name == "posix":
  pass
if os.name == "nt":
  print "You can't use Paketci on Windows"
  alt.cik()
if os.name == "mac":
  print "You can't use Paketci on Mac"
  alt.cik()

if os.popen('whoami').readline()[:-1] != "root":
	print "You have to be root in order to install Paketci"
	sys.exit()
	

ana_dizin = os.getcwd()


os.system("echo -e '\E[0;31m'\"\033[1m------------------------\033[0m\"")
os.system("echo -e '\E[0;32m'\"\033[1mPaketçi Prealpha2.2\033[0m\"")
os.system("echo -e '\E[0;32m'\"\033[1mBerat Alp Erbil 2015\033[0m\"")
os.system("echo -e '\E[0;31m'\"\033[1m------------------------\033[0m\"")
print "This app is still at testing state. \nDo not install if you aren't a tester."
onay=raw_input("If you agree GPLv2 license please enter \"yes\": ")
if onay == "evet":
	pass
else:
	sys.exit()
	
	

os.system("echo -e '\E[0;32m'\"\033[1mList of Dependencies\033[0m\"")
print "wget; for update system"
print "tar; for extracting archives"
print "bsdtar; for extracting packages"
time.sleep(3)
  
print """
List of Changes
Initial translation to English
Basic installation process

Known Issues
You have to enter the full path when installing RPM package.

"""
time.sleep(5)
# Önce eski bir kurulum var mı diye bakıyoruz.
if os.path.isdir("/usr/share/paketci"):
	os.system("echo -e '\E[0;32m'\"\033[1mFound an old version of Paketci, updating...\033[0m\"")
else:
	# Kurulum dizinlerini oluşturuyoruz.
	os.chdir("/usr/share")
	os.system("mkdir paketci")
	os.chdir("/usr/share/paketci")
	os.system("mkdir gecici")
	os.system("mkdir kayit")
	os.system("mkdir /usr/share/paketci/src/")
	os.system("mkdir /usr/share/paketci/src/gecici")

	# Kayıt dizini altına desteklenen dağıtımlar için birer klasör açıyoruz.
	os.chdir("/usr/share/paketci/kayit")
	os.system("mkdir debian")
    os.system("mkdir redhat")


# Gerekli dosyaları kurulum dizinine kopyalıyoruz ve sembolik bağı oluşturuyoruz.
os.chdir(ana_dizin)
print "\nCopying files..."
os.system("cp paketci /usr/share/paketci -f")
os.system("cp aletkutusu.py /usr/share/paketci -f")
os.system("cp debian.py /usr/share/paketci -f")
os.system("cp rpm.py /usr/share/paketci -f")
os.system("cp paketci_kaldir.py /usr/share/paketci -f")
os.system("cp paketci_yapilandir.py /usr/share/paketci -f")
print "-----------------------------------"
print "Installing files for RPM support..."
os.system("cp rpm2cpio /usr/bin -f")
os.system("cp rpmextract /usr/bin -f")
os.system("chmod a+x /usr/bin/rpm2cpio")
os.system("mkdir /usr/share/paketci/rpm")
os.system("mkdir /usr/share/paketci/rpm/gecici")
os.system("mkdir /usr/share/paketci/rpm/kayit")


if os.path.isfile("/usr/bin/paketci"):
	pass
else:
	os.system("ln -s /usr/share/paketci/paketci /usr/bin/paketci")
if os.path.isfile("/usr/share/paketci/yapilandir.txt"):
  print "Update successfully completed."
  sys.exit()
print "-------------------------"
print "Starting configuration"
print "-------------------------"
os.system("paketci yapilandir")
print "End of configuratiom"
#Kurulum tamam, kullanıcıyı bilgilendiriyoruz.
os.system("echo -e '\E[0;31m'\"\033[1m------------------------\033[0m\"")
print "Installation has finished!\nYou can start Paketci by typing \"paketci\" in termimal.\nNo errors were reported."







